name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS credentials-
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Expose GitHub Runtime # For GitHub cache
      uses: crazy-max/ghaction-github-runtime@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push via bake
      uses: docker/bake-action@v4
      with:
        push: true
        files: docker-compose.yaml,docker-bake.hcl
        set: |
          *.cache-from=type=gha
          *.cache-to=type=gha,mode=max
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
