name: Deploy to ECR and Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build image via Bake and Push to ECR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ap-northeast-1
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Expose GitHub Runtime # For GitHub cache
      uses: crazy-max/ghaction-github-runtime@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push via bake
      uses: docker/bake-action@v4
      with:
        push: true
        files: docker-bake.hcl
        provenance: false # https://github.com/docker/build-push-action/issues/755#issuecomment-1378273495
        set: |
          *.cache-from=type=gha
          *.cache-to=type=gha,mode=max
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

